<?php
/**
 * @file
 * Code for the RedHen Raiser Core feature.
 */

include_once 'redhen_raiser_core.features.inc';

/**
 * Implements hook_menu().
 */
function redhen_raiser_core_menu() {
  $items = array();

  $items['fundraise'] = array(
    'title' => 'Become a Fundraiser',
    'access callback' => TRUE,
    'page callback' => 'redhen_raiser_core_fundraise_now_page',
    'page arguments' => array(),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Return the UI for creating a fundraiser.
 * 
 * If the user is not authenticated, gives them an authentication workflow.
 */
function redhen_raiser_core_fundraise_now_page() {
  if (user_is_anonymous()) {
    $register_options = array(
      'query' => array(
        'action' => 'register',
      ),
    );
    if (isset($_GET['action'])) {
      switch ($_GET['action']) {
        case "register":
          $form = redhen_raiser_register_form(array(), 'fundraise');
          break;

        case "reset":
          $form = redhen_raiser_password_form(array(), $register_options, 'fundraise');
          break;
      }
    }
    else {
      $password_options = array(
        'query' => array(
          'action' => 'reset',
        ),
      );
      $form = redhen_raiser_login_form($register_options, $password_options, 'fundraise');
    }
    return drupal_render($form);
  }
  else {
    return 'go for it';
  }
}

/**
 * A customized version of the login form.
 */
function redhen_raiser_login_form($register_options = array(), $reset_options = array(), $override_link = FALSE) {
  $content = drupal_get_form('user_login');
  $content['name']['#description'] = NULL;
  $content['pass']['#description'] = NULL;
  $content['actions']['submit']['#value'] = "Log In";
  $content['register'] = array(
    '#type' => 'link',
    '#title' => t("Don't have an account? Create one."),
    '#href' => $override_link ? $override_link : 'user/register',
    '#options' => $register_options,
    '#weight' => 20,
  );
  $content['reset'] = array(
    '#type' => 'link',
    '#title' => t("Forgot your password? Reset it."),
    '#href' => $override_link ? $override_link : 'user/password',
    '#options' => $reset_options,
    '#weight' => 21,
  );
  return $content;
}

/**
 * A customized version of the registration form.
 */
function redhen_raiser_register_form($login_options = array(), $override_link = FALSE) {
  $content = drupal_get_form('user_register_form');
  $content['account']['name']['#description'] = NULL;
  $content['account']['mail']['#description'] = NULL;
  $content['account']['pass']['#description'] = NULL;
  $content['actions']['submit']['#value'] = "Create Account";
  // Fix up the RedHen form:
  unset($content['redhen_contact']['#title']);
  $content['redhen_contact']['#weight'] = $content['account']['#weight'] - .1;
  $allowed_fields = array('name');
  foreach (element_children($content['redhen_contact']['form']) as $fieldname) {
    $field = &$content['redhen_contact']['form'][$fieldname];
    if (!in_array($fieldname, $allowed_fields) && !$field['#required']) {
      $field['#access'] = FALSE;
    }
  }
  $content['redhen_contact']['form']['name']['middle_name']['#access'] = FALSE;
  $content['login'] = array(
    '#type' => 'link',
    '#title' => t("Already have an account? Sign in."),
    '#href' => $override_link ? $override_link : 'user/login',
    '#options' => $login_options,
    '#weight' => 20,
  );
  $content['actions']['cancel'] = array(
    '#type' => 'link',
    '#title' => t('Cancel'),
    '#href' => $override_link ? $override_link : 'home',
    '#weight' => 100,
  );
  $content['redhen_contact']['account'] = $content['account'];
  unset ($content['account']);
  return $content;
}


/**
 * A customized version of the password reset form.
 */
function redhen_raiser_password_form($login_options = array(), $register_options = array(), $override_link = FALSE) {
  module_load_include('inc', 'user', 'user.pages');
  $content = drupal_get_form('user_pass');
  $content['account']['mail']['#description'] = NULL;
  $content['account']['pass']['#description'] = NULL;
  $content['actions']['submit']['#value'] = "Reset Password";
  $content['login'] = array(
    '#type' => 'link',
    '#title' => t("Already have an account? Sign in."),
    '#href' => $override_link ? $override_link : 'user/login',
    '#options' => $login_options,
    '#weight' => 20,
  );
  $content['register'] = array(
    '#type' => 'link',
    '#title' => t("Don't have an account? Create one."),
    '#href' => $override_link ? $override_link : 'user/register',
    '#options' => $register_options,
    '#weight' => 21,
  );
  $content['actions']['cancel'] = array(
    '#type' => 'link',
    '#title' => t('Cancel'),
    '#href' => $override_link ? $override_link : 'home',
    '#weight' => 100,
  );
  return $content;
}
