<?php
/**
 * @file
 * Drupal needs this blank file.
 */

/**
 * Implements hook_menu().
 */
function redhen_raiser_core_menu() {
  $items = array();

  $items['fundraise'] = array(
    'title' => 'Fundraise Now',
    'access callback' => TRUE,
    'page callback' => 'redhen_raiser_core_fundraise_now_page',
    'page arguments' => array(),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function redhen_raiser_core_fundraise_now_page() {
  if (user_is_anonymous()) {
    $login_options = array(
      'query' => array(
        'destination' => 'fundraise',
      ),
    );
    $register_options = array(
      'query' => array(
        'destination' => 'fundraise',
        'action' => 'register',
      ),
    );
    if (isset($_GET['action'])) {
      switch ($_GET['action']) {
        case "register":
          $form = redhen_raiser_register_form($login_options, 'fundraise');
          break;

        case "reset":
          $form = redhen_raiser_password_form($login_options, $register_options, 'fundraise');
          break;
      }
    }
    else {
      $password_options = array(
        'query' => array(
          'destination' => 'fundraise',
          'action' => 'reset',
        ),
      );
      $form = redhen_raiser_login_form($register_options, $password_options, 'fundraise');
    }
    return drupal_render($form);
  }
  else {
    return "hello";
  }
}

function redhen_raiser_login_form($register_options = array(), $reset_options = array(), $override_link = FALSE) {
  $content = drupal_get_form('user_login');
  $content['name']['#description'] = NULL;
  $content['pass']['#description'] = NULL;
  $content['register'] = array(
    '#type' => 'link',
    '#title' => t("Don't have an account? Create one."),
    '#href' => $override_link ? $override_link : 'user/register',
    '#options' => $register_options,
    '#weight' => 20,
  );
  $content['reset'] = array(
    '#type' => 'link',
    '#title' => t("Forgot your password? Reset it."),
    '#href' => $override_link ? $override_link : 'user/password',
    '#options' => $reset_options,
    '#weight' => 21,
  );
  $block['subject'] = t('Login');
  $block['content'] = $content;
  return $content;
}

function redhen_raiser_register_form($login_options = array(), $override_link = FALSE) {
  $content = drupal_get_form('user_register_form');
  $content['account']['name']['#description'] = NULL;
  $content['account']['mail']['#description'] = NULL;
  $content['account']['pass']['#description'] = NULL;
  $content['login'] = array(
    '#type' => 'link',
    '#title' => t("Already have an account? Sign in."),
    '#href' => $override_link ? $override_link : 'user/login',
    '#options' => $login_options,
    '#weight' => 20,
  );
  $block['subject'] = t('Create Account');
  $block['content'] = $content;
  return $content;
}

function redhen_raiser_password_form($login_options = array(), $register_options = array(), $override_link = FALSE) {
  module_load_include('inc', 'user', 'user.pages');
  $content = drupal_get_form('user_pass');
  $content['account']['mail']['#description'] = NULL;
  $content['account']['pass']['#description'] = NULL;
  $content['login'] = array(
    '#type' => 'link',
    '#title' => t("Already have an account? Sign in."),
    '#href' => $override_link ? $override_link : 'user/login',
    '#options' => $login_options,
    '#weight' => 20,
  );
  $content['register'] = array(
    '#type' => 'link',
    '#title' => t("Don't have an account? Create one."),
    '#href' => $override_link ? $override_link : 'user/register',
    '#options' => $register_options,
    '#weight' => 21,
  );
  $block['subject'] = t('Reset Password');
  $block['content'] = $content;
  return $content;
}
