<?php
/**
 * @file
 * Code for the RedHen Raiser Blocks & Widgets feature.
 */

include_once 'redhen_raiser_blocks.features.inc';

/**
 * Implements hook_block_info().
 */
function redhen_raiser_blocks_block_info() {
  $blocks = array();

  $blocks['campaign_progress'] = array(
    'info' => t('Campaign Progress'),
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  $blocks['campaign_page_progress'] = array(
    'info' => t('Campaign Page Progress'),
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function redhen_raiser_blocks_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'campaign_progress':
      $block['content'] = redhen_raiser_blocks_campaign_progress();
      break;

    case 'campaign_page_progress':
      $block['content'] = redhen_raiser_blocks_campaign_page_progress();
      break;
  }

  return $block;
}

/**
 * Implements hook_block_view_alter().
 */
function redhen_raiser_blocks_block_view_alter(&$data, $block) {
  if ($block->module == 'bean') {
    $bean = &$data['content']['bean'][$block->delta];
    switch ($bean['#bundle']) {
      case "promo":
        // Link the Promo bean image to the target link.
        if (isset($bean['field_promo_image'])) {
          if (isset($bean['field_promo_image_link'])) {
            $bean['field_promo_image'][0]['#path']['path'] = $bean['field_promo_image_link']['#items'][0]['url'];
            $bean['field_promo_image_link']['#access'] = FALSE;
          }
          else {
            unset($bean['field_promo_image'][0]['#path']);
          }
        }
        break;

    }
  }
}

/**
 * Create default Blocks.
 */
function redhen_raiser_create_default_blocks() {

  $stubbed_beans = array(
    // Link beans.
    'social_media_links' => array(
      'type' => 'link_group',
      'label' => 'Social Media Links',
      'title' => '',
      'properties' => array(
        'field_links' => array(
          array(
            'url' => 'http://www.twitter.com',
            'title' => 'Twitter',
            'attributes' => array('class' => 'twitter-link'),
          ),
          array(
            'url' => 'http://www.facebook.com',
            'title' => 'Facebook',
            'attributes' => array('class' => 'facebook-link'),
          ),
          array(
            'url' => 'http://www.linkedin.com',
            'title' => 'LinkedIn',
            'attributes' => array('class' => 'linkedin-link'),
          ),
          array(
            'url' => 'http://plus.google.com',
            'title' => 'Google+',
            'attributes' => array('class' => 'googleplus-link'),
          ),
        ),
      ),
    ),
  );
  redhen_raiser_create_beans($stubbed_beans);
}

/**
 * Helper to create beans.
 */
function redhen_raiser_create_beans($stubbed_beans) {
  foreach ($stubbed_beans as $name => $stubbed_bean) {
    $new_bean = bean_create(array('type' => $stubbed_bean['type']));
    $new_bean->label = $stubbed_bean['label'];
    $new_bean->title = $stubbed_bean['title'];
    $new_bean->delta = $name;
    if (!empty($stubbed_bean['data'])) {
      $new_bean->data = $stubbed_bean['data'];
    }
    $bean_wrapper = entity_metadata_wrapper('bean', $new_bean);
    foreach ($stubbed_bean['properties'] as $prop => $value) {
      if (strpos($bean_wrapper->field_links->type(), 'list<') === FALSE) {
        $bean_wrapper->{$prop} = $value;
      }
      else {
        foreach ($value as $item) {
          $bean_wrapper->{$prop}[] = $item;
        }
      }
    }
    $new_bean->save();
  }
}

/**
 * Content for a block with campaign progress information.
 */
function redhen_raiser_blocks_campaign_progress() {
  if (arg(0) != 'redhen_campaign') {
    return array();
  }
  if (arg(1) == "page") {
    $page = redhen_campaign_page_load(arg(2));
    $campaign_id = $page->campaign;
  }
  else {
    $campaign_id = arg(1);
  }
  $campaign = redhen_campaign_load($campaign_id);
  $content = entity_view('redhen_campaign', array($campaign), 'progress', NULL, TRUE);
  return $content;
}


/**
 * Content for a block with campaign progress information.
 */
function redhen_raiser_blocks_campaign_page_progress() {
  if (arg(0) != 'redhen_campaign' || arg(1) != "page") {
    return array();
  }
  $page = redhen_campaign_page_load(arg(2));
  $content = entity_view('redhen_campaign_page', array($page), 'progress', NULL, TRUE);
  return $content;
}
