<?php
/**
 * @file
 * Code for the RedHen Raiser Blocks & Widgets feature.
 */

include_once 'redhen_raiser_blocks.features.inc';

/**
 * Implements hook_entity_view_alter().
 */
function redhen_raiser_blocks_entity_view_alter(&$build, $type) {
  switch ($type) {
    case "bean":
      if ($build['#bundle'] == 'promo') {
        if (isset($build['field_promo_image'])) {
          if (isset($build['field_promo_image_link'])) {
            $build['field_promo_image'][0]['#path']['path'] = $build['field_promo_image_link']['#items'][0]['url'];
            $build['field_promo_image_link']['#access'] = FALSE;
          }
          else {
            unset($build['field_promo_image'][0]['#path']);
          }
        }
      }
      break;

    case "redhen_campaign_page":
      if ($build['#view_mode'] == 'progress') {
        $parent = redhen_campaign_load($build['#entity']->campaign);
        $build['field_start_date'] = field_view_field('redhen_campaign', $parent, 'field_start_date', 'progress');
        _redhen_raiser_blocks_format_dates($build);
      }
      break;

    case "redhen_campaign":
      if ($build['#view_mode'] == 'progress') {
        _redhen_raiser_blocks_format_dates($build);
      }
      break;

  }
}

function _redhen_raiser_blocks_format_dates(&$build) {
  if (isset($build['field_start_date'])) {
    $start = strtotime($build['field_start_date']['#items'][0]['value']);
    if (time() < $start) {
      $prepend = '<span class="date-display-interval-all">';
      $prepend .= "Fundraiser begins in ";
      $build['field_start_date'][0]['#markup'] = $prepend . $build['field_start_date'][0]['#markup'] . "</span>";
      $build['field_end_date']['#access'] = FALSE;
    }
    else {
      $build['field_start_date']['#access'] = FALSE;
    }
  }
  if (isset($build['field_end_date'])) {
    $end = strtotime($build['field_end_date']['#items'][0]['value']);
    $remaining = $end - time();
    // @todo: add configuration options to control these behaviors.
    if ($remaining <= 0) {
      $build['field_end_date'][0]['#markup'] = '<span class="date-display-interval-past">Fundraiser has ended.</span>';
    }
    else {
      $prepend = '<span class="date-display-interval-all">';
      if ($remaining < (7 * 24 * 60 * 60)) {
        $prepend .= "Only ";
      }
      $build['field_end_date'][0]['#markup'] = $prepend . $build['field_end_date'][0]['#markup'] . " left.</span>";
    }
  }
}


/**
 * Create default Blocks.
 */
function redhen_raiser_blocks_create_default_blocks() {

  $stubbed_beans = array(
    // Link beans.
    'social_media_links' => array(
      'type' => 'link_group',
      'label' => 'Social Media Links',
      'title' => '',
      'properties' => array(
        'field_links' => array(
          array(
            'url' => 'http://www.twitter.com',
            'title' => 'Twitter',
            'attributes' => array('class' => 'twitter-link'),
          ),
          array(
            'url' => 'http://www.facebook.com',
            'title' => 'Facebook',
            'attributes' => array('class' => 'facebook-link'),
          ),
          array(
            'url' => 'http://www.linkedin.com',
            'title' => 'LinkedIn',
            'attributes' => array('class' => 'linkedin-link'),
          ),
          array(
            'url' => 'http://plus.google.com',
            'title' => 'Google+',
            'attributes' => array('class' => 'googleplus-link'),
          ),
        ),
      ),
    ),
    'campaign-page-progress' => array(
      'type' => 'bean_entity_view',
      'label' => 'Campaign Page Progress',
      'title' => '',
      'data' => array(
        'entity_type' => 'redhen_campaign_page',
        'entity_view_mode' => 'progress',
        'entity_id_position' => '2',
      ),
    ),
    'campaign-progress' => array(
      'type' => 'bean_entity_view',
      'label' => 'Campaign Progress',
      'title' => '',
      'data' => array(
        'entity_type' => 'redhen_campaign',
        'entity_view_mode' => 'progress',
        'entity_id_position' => '1',
      ),
    ),
    'campaign-page-banner' => array(
      'type' => 'bean_entity_view',
      'label' => 'Campaign Page Banner',
      'title' => '',
      'data' => array(
        'entity_type' => 'redhen_campaign_page',
        'entity_view_mode' => 'banner',
        'entity_id_position' => '2',
      ),
    ),
    'campaign-banner' => array(
      'type' => 'bean_entity_view',
      'label' => 'Campaign Banner',
      'title' => '',
      'data' => array(
        'entity_type' => 'redhen_campaign',
        'entity_view_mode' => 'banner',
        'entity_id_position' => '1',
      ),
    ),
    'campaign-promotion' => array(
      'type' => 'bean_entity_view',
      'label' => 'Campaign Promotion',
      'title' => '',
      'data' => array(
        'entity_type' => 'redhen_campaign',
        'entity_view_mode' => 'promotion',
        'entity_id_position' => '1',
      ),
    ),
    'campaign-page-promotion' => array(
      'type' => 'bean_entity_view',
      'label' => 'Campaign Page Promotion',
      'title' => '',
      'data' => array(
        'entity_type' => 'redhen_campaign_page',
        'entity_view_mode' => 'promotion',
        'entity_id_position' => '2',
      ),
    ),
  );
  redhen_raiser_create_beans($stubbed_beans);
}

/**
 * Helper to create beans.
 */
function redhen_raiser_create_beans($stubbed_beans) {
  foreach ($stubbed_beans as $name => $stubbed_bean) {
    $new_bean = bean_create(array('type' => $stubbed_bean['type']));
    $new_bean->label = $stubbed_bean['label'];
    $new_bean->title = $stubbed_bean['title'];
    $new_bean->delta = $name;
    if (!empty($stubbed_bean['data'])) {
      $new_bean->data = $stubbed_bean['data'];
    }
    $bean_wrapper = entity_metadata_wrapper('bean', $new_bean);
    if (!empty($stubbed_bean['properties'])) {
      foreach ($stubbed_bean['properties'] as $prop => $value) {
        if (strpos($bean_wrapper->field_links->type(), 'list<') === FALSE) {
          $bean_wrapper->{$prop} = $value;
        }
        else {
          foreach ($value as $item) {
            $bean_wrapper->{$prop}[] = $item;
          }
        }
      }
    }
    $new_bean->save();
  }
}
