<?php
/**
 * @file
 * Code for the RedHen Raiser Blocks & Widgets feature.
 */

include_once 'redhen_raiser_blocks.features.inc';

/**
 * Implements hook_block_view_alter().
 */
function redhen_raiser_blocks_block_view_alter(&$data, $block) {
  if ($block->module == 'bean') {
    $bean = &$data['content']['bean'][$block->delta];
    switch ($bean['#bundle']) {
      case "promo":
        // Link the Promo bean image to the target link.
        if (isset($bean['field_promo_image'])) {
          if (isset($bean['field_promo_image_link'])) {
            $bean['field_promo_image'][0]['#path']['path'] = $bean['field_promo_image_link']['#items'][0]['url'];
            $bean['field_promo_image_link']['#access'] = FALSE;
          }
          else {
            unset($bean['field_promo_image'][0]['#path']);
          }
        }
        break;

    }
  }
}

/**
 * Create default Blocks.
 */
function redhen_raiser_create_default_blocks() {

  $stubbed_beans = array(
    // Link beans.
    'social_media_links' => array(
      'type' => 'link_group',
      'label' => 'Social Media Links',
      'title' => '',
      'properties' => array(
        'field_links' => array(
          array(
            'url' => 'http://www.twitter.com',
            'title' => 'Twitter',
            'attributes' => array('class' => 'twitter-link'),
          ),
          array(
            'url' => 'http://www.facebook.com',
            'title' => 'Facebook',
            'attributes' => array('class' => 'facebook-link'),
          ),
          array(
            'url' => 'http://www.linkedin.com',
            'title' => 'LinkedIn',
            'attributes' => array('class' => 'linkedin-link'),
          ),
          array(
            'url' => 'http://plus.google.com',
            'title' => 'Google+',
            'attributes' => array('class' => 'googleplus-link'),
          ),
        ),
      ),
    ),
    'campaign-page-progress' => array(
      'type' => 'bean_entity_view',
      'label' => 'Campaign Page Progress',
      'title' => '',
      'data' => array(
        'entity_type' => 'redhen_campaign_page',
        'entity_view_mode' => 'progress',
        'entity_id_position' => '2',
      ),
    ),
    'campaign-progress' => array(
      'type' => 'bean_entity_view',
      'label' => 'Campaign Progress',
      'title' => '',
      'data' => array(
        'entity_type' => 'redhen_campaign',
        'entity_view_mode' => 'progress',
        'entity_id_position' => '1',
      ),
    ),
    'campaign-page-banner' => array(
      'type' => 'bean_entity_view',
      'label' => 'Campaign Page Banner',
      'title' => '',
      'data' => array(
        'entity_type' => 'redhen_campaign_page',
        'entity_view_mode' => 'banner',
        'entity_id_position' => '1',
      ),
    ),
    'campaign-banner' => array(
      'type' => 'bean_entity_view',
      'label' => 'Campaign Banner',
      'title' => '',
      'data' => array(
        'entity_type' => 'redhen_campaign',
        'entity_view_mode' => 'banner',
        'entity_id_position' => '1',
      ),
    ),
  );
  redhen_raiser_create_beans($stubbed_beans);
}

/**
 * Helper to create beans.
 */
function redhen_raiser_create_beans($stubbed_beans) {
  foreach ($stubbed_beans as $name => $stubbed_bean) {
    $new_bean = bean_create(array('type' => $stubbed_bean['type']));
    $new_bean->label = $stubbed_bean['label'];
    $new_bean->title = $stubbed_bean['title'];
    $new_bean->delta = $name;
    if (!empty($stubbed_bean['data'])) {
      $new_bean->data = $stubbed_bean['data'];
    }
    $bean_wrapper = entity_metadata_wrapper('bean', $new_bean);
    foreach ($stubbed_bean['properties'] as $prop => $value) {
      if (strpos($bean_wrapper->field_links->type(), 'list<') === FALSE) {
        $bean_wrapper->{$prop} = $value;
      }
      else {
        foreach ($value as $item) {
          $bean_wrapper->{$prop}[] = $item;
        }
      }
    }
    $new_bean->save();
  }
}
