<?php

/**
 * Implements hook_menu().
 */
function commerce_recurring_ui_menu() {
  $items = array();

  $items['admin/commerce/recurring-entities/%commerce_recurring/edit'] = array(
    'title' => 'Edit',
    'page callback' => 'entity_ui_get_form',
    'page arguments' => array('commerce_recurring', 3),
    'access callback' => 'commerce_recurring_access',
    'access arguments' => array('update', 3),
    'type' => MENU_LOCAL_TASK,
    'weight' => -5,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
    'file' => 'commerce_recurring_ui.admin.inc',
  );
  $items['admin/commerce/recurring-entities/%commerce_recurring/delete'] = array(
    'title' => 'Delete',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('commerce_recurring_ui_delete_confirm_form', 3),
    'access callback' => 'commerce_recurring_access',
    'access arguments' => array('delete', 3),
    'type' => MENU_LOCAL_TASK,
    'weight' => 20,
    'context' => MENU_CONTEXT_INLINE,
    'file' => 'commerce_recurring_ui.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_entity_info_alter().
 */
function commerce_recurring_ui_entity_info_alter(&$entity_info) {
  // @TODO: Add order bundle support when it's time for it.
  $entity_info['commerce_recurring']['bundles']['product']['admin'] = array(
    'path' => 'admin/commerce/recurring-entities/product',
    'access arguments' => array('administer commerce_recurring entities'),
  );

  // Enable the entity API's admin UI.
  $entity_info['commerce_recurring']['admin ui'] = array(
    'path' => 'admin/commerce/recurring-entities',
    'file' => 'commerce_recurring_ui.admin.inc',
  );
}

/**
 * Implements hook_views_api().
 */
function commerce_recurring_ui_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'commerce_recurring_ui') . '/includes/views',
  );
}
