<?php
/**
 * @file
 * Code for the RedHen Raiser Contacts feature.
 */

include_once 'redhen_raiser_contacts.features.inc';

/**
 * Implements hook_entity_info_alter().
 */
function redhen_raiser_contacts_entity_info_alter(&$entity_info) {
  $entity_info['redhen_contact']['view modes']['byline'] = array(
    'label' => t('Byline'),
    'custom settings' => TRUE,
  );
}

/**
 * Implements hook_entity_view_alter().
 */
function redhen_raiser_contacts_entity_view_alter(&$build, $type) {
  if ($type == 'redhen_contact') {
    $contact_wrapper = entity_metadata_wrapper("redhen_contact", $build['#entity']);
    $user = $contact_wrapper->user->value();
    $add_picture = FALSE;
    switch ($build['#view_mode']) {
      case "byline":
        $build['name']['#label'] = 'By';
        $add_picture = TRUE;
        break;

      case "redhen_campaign_page_owner":
        $add_picture = TRUE;
        break;

    }
    if ($add_picture && $user->picture) {
      $build['avatar'] = array(
        '#theme' => 'image_style',
        '#path' => $user->picture->uri,
        '#style_name' => 'avatar',
      );
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Hide the complex version of the email address form from users.
 */
function redhen_raiser_contacts_form_user_profile_form_alter(&$form, &$form_state, $form_id) {
  $form['redhen_contact']['redhen_contact_email']['#access'] = user_access('administer redhen contacts');
}

/**
 * Implements hook_menu_alter().
 */
function redhen_raiser_contacts_menu_alter(&$items) {
  $items['user/%user_category/edit/redhen_contact']['title arguments'][0] = "Contact Details";
}
