<?php
/**
 * @file
 * Code for the RedHen Raiser Donations feature.
 */

include_once 'redhen_raiser_donations.features.inc';

/**
 * Implements hook_commerce_line_item_type_info().
 *
 * @see http://www.drupalcommerce.org/specification/info-hooks/checkout
 */
function redhen_raiser_donations_commerce_line_item_type_info() {

  $line_item_types['redhen_raiser_donation'] = array(
    'name' => t('Donation'),
    'description' => t('Donation where the amount is customizable.'),
    'product' => TRUE,
    'add_form_submit_value' => t('Add donation'),
    'base' => 'commerce_product_line_item',
  );
  return $line_item_types;
}

/**
 * Implements hook_menu_alter().
 */
function redhen_raiser_donations_menu_alter(&$items) {
  if (isset($items['redhen_campaign/%redhen_campaign/donate'])) {
    $items['redhen_campaign/%redhen_campaign/donate']['type'] = MENU_NORMAL_ITEM;
  }
}

/**
 * Implements hook_menu().
 */
function redhen_raiser_donations_menu() {
  $items = array();

  $items['redhen/donation_reports'] = array(
    'title' => 'Donation Reports',
    'access callback' => 'user_access',
    'access arguments' => array('view redhen_raiser_donation redhen donation'),
    'page callback' => 'drupal_goto',
    'page arguments' => array('redhen/donations'),
  );
  return $items;
}

/**
 * Implements hook_form_alter().
 */
function redhen_raiser_donations_form_redhen_donation_form_alter(&$form, &$form_state, $form_id) {
  $parent_entity = entity_load_single($form['#entity']->entity_type, $form['#entity']->entity_id);
  $parent_wrapper = entity_metadata_wrapper($form['#entity']->entity_type, $parent_entity);
  if (!isset($parent_wrapper->field_allow_dedication) || !$parent_wrapper->field_allow_dedication->value()) {
    field_group_hide_field_groups($form, array('group_tribute'));
  }
  elseif (isset($form['field_tribute_address']) && isset($form['field_letter_request'])) {
    $form['field_tribute_address']['#states']['invisible'] = array(
      ':input[name="field_letter_request[und]"]' => array('checked' => FALSE),
    );
  }
}
