<?php
/**
 * @file
 * Code for the RedHen Raiser Campaign Pages feature.
 */

include_once 'redhen_raiser_campaign_pages.features.inc';

/**
 * Implements hook_views_pre_render().
 *
 * Put the Campaign name into the campaign pages view title.
 */
function redhen_raiser_campaign_pages_views_pre_render(&$view) {
  if ($view->name == "campaign_pages" && $view->current_display == "campaign_pages") {
    $campaign = redhen_campaign_load($view->args[0]);
    $title_pattern = $view->build_info['title'];
    foreach ($view->build_info['substitutions'] as $needle => $value) {
      $title_pattern = str_replace($needle, $value, $title_pattern);
    }
    $new_title = str_replace($view->args[0], $campaign->label, $title_pattern);
    $view->set_title($new_title);
  }
}

/**
 * Implements hook_entity_info_alter().
 */
function redhen_raiser_campaign_pages_entity_info_alter(&$entity_info) {
  $entity_info['redhen_campaign_page']['view modes']['progress'] = array(
    'label' => t('Progress'),
    'custom settings' => TRUE,
  );
  $entity_info['redhen_campaign_page']['view modes']['banner'] = array(
    'label' => t('Banner'),
    'custom settings' => TRUE,
  );
}

/**
 * Implements hook_entity_view_alter().
 */
function redhen_raiser_campaign_pages_entity_view_alter(&$build, $type) {
  if ($type == 'redhen_campaign') {
    if ($build['#view_mode'] == 'teaser') {
      // Link the label.
      if (!empty($build['label']['#items'][0]['#markup'])) {
        $uri = $build['#entity']->uri();
        $path = $uri['path'];

        $build['label']['#items'][0]['#markup'] = l(
          $build['label']['#items'][0]['#markup'],
          $path
        );
      }
    }
    if ($build['#view_mode'] == 'full') {
      $options = array(
        'attributes' => array(
          'class' => 'redhen-campaign-pages-button',
        ),
      );
      $build['pages'] = array(
        '#markup' => l(t('View all Teams and Individuals'), 'campaigns/' . $build['#entity']->campaign_id . '/pages', $options),
        '#weight' => 100,
      );
    }
  }

  if ($type == 'redhen_campaign_page') {
    if ($build['#view_mode'] == 'teaser') {
      $uri = $build['#entity']->uri();
      $path = $uri['path'];

      // Link the label.
      if (!empty($build['label']['#items'][0]['#markup'])) {
        $build['label']['#items'][0]['#markup'] = l(
          $build['label']['#items'][0]['#markup'],
          $path
        );
      }

      // Link the image.
      if (!empty($build['owner']['redhen_contact'])) {
        foreach ($build['owner']['redhen_contact'] as $contact_id => $contact) {
          $build['owner']['redhen_contact'][$contact_id]['avatar']['#post_render'] = array(
            '_redhen_raiser_campaign_pages_contact_image_post_render',
          );
          $build['owner']['redhen_contact'][$contact_id]['avatar']['link_url'] = $path;
        }
      }
    }
    if ($build['#view_mode'] == 'full') {
      if (isset($build['campaign'])) {
        _redhen_raiser_campaign_pages_colectomify($build['campaign']);
        $build['campaign']['#label'] = 'Fundraising for';
        unset($build['campaign']['#label_hidden']);
      }
      if (isset($build['team'])) {
        _redhen_raiser_campaign_pages_colectomify($build['team']);
        $build['team']['#label'] = 'with';
      }
    }
  }
}

/**
 * Helper to allow field_extra_fields enabled properties to be colectomified.
 *
 * See the colectomy module.
 */
function _redhen_raiser_campaign_pages_colectomify(&$field) {
  $field['#label_display'] = 'inlinec';
  $field['#post_render'] = array('colectomy' => 'colectomy_post_render');
}

/**
 * Post-render callback to link an image to the designated campaign page.
 */
function _redhen_raiser_campaign_pages_contact_image_post_render($html, $variables) {
  $linked_img = l($html, $variables['link_url'], array('html' => TRUE));

  return $linked_img;
}
