<?php
/**
 * @file
 * Code for the RedHen Raiser Campaign Pages feature.
 */

include_once 'redhen_raiser_campaign_pages.features.inc';

/**
 * Implements hook_views_pre_render().
 *
 * Put the Campaign name into the campaign pages view title.
 */
function redhen_raiser_campaign_pages_views_pre_render(&$view) {
  if ($view->name == "campaign_pages" && $view->current_display == "campaign_pages") {
    $campaign = redhen_campaign_load($view->args[0]);
    $title_pattern = $view->build_info['title'];
    foreach ($view->build_info['substitutions'] as $needle => $value) {
      $title_pattern = str_replace($needle, $value, $title_pattern);
    }
    $new_title = str_replace($view->args[0], $campaign->label, $title_pattern);
    if ($campaign) {
      $new_title = str_replace('$campaign_id', $campaign->campaign_id, $new_title);
    }
    $view->set_title($new_title);
  }
}

/**
 * Implements hook_entity_info_alter().
 */
function redhen_raiser_campaign_pages_entity_info_alter(&$entity_info) {
  $entity_info['redhen_campaign_page']['view modes']['progress'] = array(
    'label' => t('Progress'),
    'custom settings' => TRUE,
  );
  $entity_info['redhen_campaign_page']['view modes']['snippet'] = array(
    'label' => t('Snippet'),
    'custom settings' => TRUE,
  );
  $entity_info['redhen_campaign_page']['view modes']['banner'] = array(
    'label' => t('Banner'),
    'custom settings' => TRUE,
  );
  $entity_info['redhen_campaign_page']['view modes']['promotion'] = array(
    'label' => t('Promo'),
    'custom settings' => TRUE,
  );
}

/**
 * Implements hook_entity_view_alter().
 */
function redhen_raiser_campaign_pages_entity_view_alter(&$build, $type) {
  if ($type == 'redhen_campaign_page') {
    switch ($build['#view_mode']) {
      case 'teaser':
      case 'snippet':
        $uri = $build['#entity']->uri();
        $path = $uri['path'];

        // Link the label.
        if (!empty($build['label']['#items'][0]['#markup'])) {
          $build['label']['#items'][0]['#markup'] = l(
            $build['label']['#items'][0]['#markup'],
            $path
          );
        }

        // Link the image.
        if (!empty($build['owner']['redhen_contact'])) {
          foreach ($build['owner']['redhen_contact'] as $contact_id => $contact) {
            $build['owner']['redhen_contact'][$contact_id]['avatar']['#post_render'] = array(
              '_redhen_raiser_campaign_pages_contact_image_post_render',
            );
            $build['owner']['redhen_contact'][$contact_id]['avatar']['link_url'] = $path;
          }
        }
        break;

      case 'full':
        if (isset($build['campaign'])) {
          _redhen_raiser_core_colectomify($build['campaign']);
          $build['campaign']['#label'] = 'Fundraising for';
          unset($build['campaign']['#label_hidden']);
        }
        if (isset($build['team'])) {
          _redhen_raiser_core_colectomify($build['team']);
          $build['team']['#label'] = 'with';
        }
        break;

      case 'promotion':
        $campaign = redhen_campaign_load($build['#entity']->campaign);
        $build['campaign'] = entity_view('redhen_campaign', array($campaign), 'promotion', NULL, FALSE);
        break;

    }
  }
}

/**
 * A simple form for selecting a campaign to join before creating a fundraiser.
 */
function redhen_raiser_campaign_pages_create_fundraiser_form($form, &$form_state) {
  $campaigns = redhen_raiser_campaigns_load_active();
  $options = array('' => '-- Select --');
  foreach ($campaigns as $campaign) {
    $options[$campaign->campaign_id] = $campaign->label;
  }
  $form['campaign'] = array(
    '#type' => 'select',
    '#title' => t('Which fundraising campaign would you like to join?'),
    '#options' => $options,
    '#attributes' => array('onChange' => 'document.getElementById("redhen-raiser-campaign-pages-create-fundraiser-form").submit();'),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Create Fundraiser',
    '#attributes' => array('class' => array('element-invisible')),
  );
  return $form;
}

/**
 * Form submission handler.
 */
function redhen_raiser_campaign_pages_create_fundraiser_form_submit($form, &$form_state) {
  drupal_goto('redhen_campaign_page/add', array('query' => array('campaign' => $form_state['input']['campaign'])));
}

/**
 * Post-render callback to link an image to the designated campaign page.
 */
function _redhen_raiser_campaign_pages_contact_image_post_render($html, $variables) {
  $linked_img = l($html, $variables['link_url'], array('html' => TRUE));

  return $linked_img;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function redhen_raiser_campaign_pages_form_redhen_campaign_campaign_page_form_alter(&$form, &$form_state, $form_id) {
  $form['campaign']['#access'] = user_access('administer redhen campaign pages') || empty($form_state['campaign']);
  $form['team']['#access'] = user_access('administer redhen campaign pages') || empty($form_state['team']);
}
